### ISSUE TITLE
Add an Identity Head weights 

### ISSUE THREAD

**Issue by tttonyalpha** [google-research/readout_guidance#3]
Thanks for the good paper, the open code and the models weights! In the paper you present the Identity Head, but I didn't find weights for it, can you release them?

**Comment by g-luo** [comment]
Hi! We decided not to release the weights for the identity head because it deals with human faces and has the potential for misuse. However, you can adapt the codebase for this use case with the following steps:

1. The training code for the identity head is identical to the appearance similarity head; you just need to replace the DAVIS frames with images and SDEdits from [CelebA-HQ](https://github.com/tkarras/progressive_growing_of_gans) in the [config](https://github.com/google-research/readout_guidance/blob/ba3d7611b9299e25bfba5410a3a4180443772c03/readout_training/configs/train_appearance.yaml#L48). You also need to make sure that you update the folder structure of CelebA-HQ such that the images are grouped by identity (similar to how the DAVIS frames are grouped by video).

2. The guidance code for the identity head is also the same as the appearance similarity head, but you need to add an additional argument to the `edit` such that it includes a bounding box for the face, which is used [here](https://github.com/google-research/readout_guidance/blob/ba3d7611b9299e25bfba5410a3a4180443772c03/readout_guidance/rg_operators.py#L166). Note that the intended workflow is that you first generate two images without guidance, run a [face detector](https://pypi.org/project/facenet-pytorch) to get the bounding boxes, then generate the two images again with guidance.
